spring:
  application:
    name: scamshield
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${POSTGRES_DB:scamshield}
    username: ${POSTGRES_USER:scamshield}
    password: ${POSTGRES_PASSWORD:change-me-for-local-development}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: ${SERVER_PORT:8081}
